### ISSUE TITLE
DrupalGap -- Failed to add cart form 

### ISSUE THREAD

**Issue by Abilchacko** [Shredder121-me/IssueToPr#2]
DrupalGap - In Drupal commerce - I have created a cart as per
 http://tylerfrankenstein.com/code/build-mobile-app-sell-products-with-drupal 
But Error is 
drupal_get_form - failed to get form (commerce_cart_add_to_cart_form) 
In console - commerce_cart_add_to_cart_form - TypeError: Cannot read property 'product_reference_field_name' of undefined
Product Type - Dress
Content type - Dress
Product Reference -
 Label - Dress 
## Field Name - field_dress 

In settings.js
## drupalgap.settings.commerce={bundles: {Dress:{ product_reference_field_name: 'field_dress'}}};

![trouble](https://cloud.githubusercontent.com/assets/10782453/18656226/16a36968-7f0d-11e6-9adc-37b23ea73254.jpg)

Kindly walk Through this Error and Plz help me 
Thanking a lot
Abil chacko

**Comment by Shredder121** [comment]
?
