### ISSUE TITLE
POST ?q=drupalgap/line-item.json 401 (Unauthorized : Access to this operation not granted)

### ISSUE THREAD

**Issue by Abilchacko** [Shredder121-me/IssueToPr#3]
POST ?q=drupalgap/line-item.json 401 (Unauthorized : Access to this operation not granted)

 I saw this solution line But I cant understand 
Drupal commerce does not allow anonymous user's to edit their own orders, AFAIK.
The commerce_entity_access() function and the boolean that checks for $account->uid 
won't allow anonymous users to edit their own orders even if you grant permission.

Kindly Help to solve this issue Just check this http://keralaservices.com/mobile-application/

Thanking you
 Abil chacko

**Comment by Shredder121** [comment]
Could you please explain yourself?

**Comment by Abilchacko** [comment]
DrupalGap -Error
Admin can add item to a cart
But announymus  user while adding item to cart  
Error in console is 
POST ?q=drupalgap/line-item.json 401 (Unauthorized : Access to this operation not granted)

**Comment by Abilchacko** [comment]
![drupalgap error refrence](https://cloud.githubusercontent.com/assets/10782453/18706167/8849afbc-800e-11e6-9a5d-d08357009b7a.JPG)

Check this Image

**Comment by Abilchacko** [comment]
![cart issue](https://cloud.githubusercontent.com/assets/10782453/18706192/9e56e2b6-800e-11e6-8fb1-63613e0f4a63.JPG)

Check this Image

**Comment by Shredder121** [comment]
I have nothing to do with Drupal though.
I think you're better off reporting this elsewhere.

**Comment by Shredder121** [comment]
You could also try a search on StackOverflow.

**Comment by Abilchacko** [comment]
ok thank you
